# Generated by Django 4.1 on 2022-09-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Custom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
    ]
