# Generated by Django 4.1 on 2022-09-26 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 14, 40, 8, 874571)),
        ),
    ]
