# Generated by Django 4.1 on 2022-09-26 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom', '0002_alter_transaction_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 14, 55, 54, 751517)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
